name: Build APK

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [ published ]

env:
  GRADLE_VERSION: 8.10.2
  JDK_VERSION: 17

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        flavor: [mobile, leanback]
        abi: [arm64_v8a, armeabi_v7a]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK ${{ env.JDK_VERSION }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JDK_VERSION }}
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
      
    - name: Create signing properties
      run: |
        mkdir -p keystore
        # 创建测试签名文件（实际使用时应该使用 secrets）
        keytool -genkey -v -keystore keystore/release.jks \
          -keyalg RSA -keysize 2048 -validity 10000 \
          -alias xmbox -dname "CN=Android,O=Android,C=US" \
          -storepass xmbox123 -keypass xmbox123
        
    - name: Build APK
      run: |
        ./gradlew assemble${{ matrix.flavor }}${{ matrix.abi }}Release \
          --no-daemon --stacktrace
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.flavor }}-${{ matrix.abi }}-apk
        path: app/build/outputs/apk/${{ matrix.flavor }}${{ matrix.abi }}/release/*.apk
        retention-days: 7
        
  build-all:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Download all APK artifacts
      uses: actions/download-artifact@v4
      
    - name: List generated APKs
      run: find . -name "*.apk" -type f | sort
      
    - name: Upload all APKs
      uses: actions/upload-artifact@v4
      with:
        name: all-apks
        path: |
          */mobile-arm64_v8a.apk
          */mobile-armeabi_v7a.apk
          */leanback-arm64_v8a.apk
          */leanback-armeabi_v7a.apk
        retention-days: 30
